### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by gdw2** [tjfontaine/node-path-platform#1]

**Comment by marcello3d** [comment]
Any update on this? Browserify depends on this module, and this appears to be "closed" source.

**Comment by jinder** [comment]
Any update on this?   It's MIT licensed according to the header on the path.js, but it would be good to get a LICENSE.md file and and update to the NPM package.

**Comment by tjfontaine** [comment]
The only license that matters is what's in the file, and this file comes directly from node.js upstream

fixed in 901e4d8a69ed3906bbbec5f65e9b7eec6d033474

**Comment by marcello3d** [comment]
Thank you! :-)
